### ISSUE TITLE
with fragments and dialogs.

### ISSUE THREAD

**Issue by sourabhbans007** [XunMengWinter/CircularAnim#10]
1. How can i use it with fragments and dialogs ?
2. Is it works for lower APIs than Lollipop with same effect?

thanks. :+1:

**Comment by XunMengWinter** [comment]
1. This util only support actvity, wish someone extend it ~
2. The method ViewAnimationUtils.createCircularReveal() only support api 21 or higher, so, I don't know how to achieve same effect for api 19 or lower, 囧

**Comment by XunMengWinter** [comment]
Oh, It can works with fragments, because it's just a Full-Screen view.
you can show the anim view, then change fragment, when back pressed, you can change the fragment then hide the anim view.
My English is so poor, can you understand? ~ ~

**Comment by faziltm** [comment]
This code is very helpful.
When i am using service the 
CircularAnim.fullActivity(MainActivity.this, view) it changed as CircularAnim.fullActivity(getApplicationContext(), view) Then it shows the error Wrong 1st argument type. Found: 'android.content.Context', required: 'android.app.Activity'

I have posted in http://stackoverflow.com/questions/42503363/android-not-getting-getapplicationcontext-on-service
Please help me

**Comment by DanteAndroid** [comment]
@faziltm I think you should learn some Java and Android fundamentals.

**Comment by XunMengWinter** [comment]
See this [FragmentTestActivity](https://github.com/XunMengWinter/CircularAnim/blob/master/demo/src/main/java/top/wefor/circularanimdemo/fragment/FragmentTestActivity.java)

support Fragment or any View.
