### ISSUE TITLE
又是小米..

### ISSUE THREAD

**Issue by huijimuhe** [XunMengWinter/CircularAnim#14]
以前找的statuebar、badge、推送在小米上都麻烦的要命..
这次果然activity跳转又被坑进去了..
不吐不快啊
P.S谢谢大神的作品，一个字：酷！

**Comment by XunMengWinter** [comment]
额，我的就是小米～～

**Comment by huijimuhe** [comment]
额，我的没动画效果...换联想上就有了

**Comment by XunMengWinter** [comment]
这个帮助类只支持5.0以后～～
