### ISSUE TITLE
关于JCenter的上传方法

### ISSUE THREAD

**Issue by mBigFlower** [XunMengWinter/CircularAnim#15]
- 鸿洋的微信公众号里几个月前有一片关于JCenter上传包的方法。挺简单的(无形中给鸿洋打了波广告 。。。)
- 另外之前我还试过一种，简单配置很少的东西，然后把生成的zip包手动上传到JCenter，这个虽然手动，但是确实很好用（这个方法我是在**简书**里搜到的）

希望对你有帮助哈

**Comment by XunMengWinter** [comment]
那个JCenter的得配置一页文件，然后我跟着文档，看着看着就迷路了，囧。用了JitPack,两行代码傻瓜式上传，比较适合我～～
