### ISSUE TITLE
源码中有个地方写错了吧

### ISSUE THREAD

**Issue by qinxiaoguang** [XunMengWinter/CircularAnim#20]
int cx = (myView.getLeft() + myView.getRight()) / 2;
int cy = (myView.getTop() + myView.getBottom()) / 2;

这个地方应该取得view的中心坐标吧，应该是getRight - getLeft，我测试代码的时候发现水波中心确实不在正中间。

**Comment by XunMengWinter** [comment]
注意myView的layout摆放，这个和它的父布局也有关系，比较稳妥的方法是直接在myView外面框一个FrameLayout, 把padding 和 margin之类的全丢到frameLayout中去。
