### ISSUE TITLE
几率不出现返回动画

### ISSUE THREAD

**Issue by jesse920524** [XunMengWinter/CircularAnim#21]
Activity A >> ActivityB时永远会有动画,
但Activity B 执行onBackPressed()时,有一定几率不执行收回动画;
onBackPressed()并没有@Override

Activity A >> Activity B后,
Activity B >> Activity C;
Activity C onBackPressed()回到Activity B, 此时Activity B执行onBackPressed(),不会出现返回动画

以上,只在Activity A中的onClick()中使用了
`CircularAnimUtil.startActivity(this, f2lIntent, iv_first_layout_menu, R.color.bluegrey_900);`

**Comment by XunMengWinter** [comment]
返回是调用onBackPressed()还是finish() ? 如果使用finish() ，会没有返回动画。
