### ISSUE TITLE
让按钮收缩不起作用

### ISSUE THREAD

**Issue by DanteAndroid** [XunMengWinter/CircularAnim#27]
CircularAnim.show(login).go();
 只让按钮显示 没有动画。
原因：收縮动画未完成，展开动画就开始了。可否修改逻辑仅当前一个动画完成后下一个动画才开始
 
另外，如果能开放系统动画的delay接口，就更好了。

**Comment by XunMengWinter** [comment]
你好，你可以在go()里面放一个动画结束的监听器，如
.go(new CircularAnim.OnAnimationEndListener() {
                            @Override
                            public void onAnimationEnd() {
                                //该动画结束后你要做的事情
                            }
                        });
