### ISSUE TITLE
铺满颜色启动Activity时显示延迟

### ISSUE THREAD

**Issue by qingchen1016** [XunMengWinter/CircularAnim#30]
您好，首先感谢提供这么好用的功能

我感觉铺满颜色启动页面时新页面出现有点延迟。。
也就是说全屏颜色的时候会停顿一下，
有没有办法像你在文档开头放的那张UI图那样，
颜色在刚刚铺满屏幕的时候马上显示出新的页面。

不知道这个停顿的时间是不是依赖于activity的启动时间
或者说跟设备的内存等属性也有关系
有没有可能让铺满颜色的效果像Toast那样运行在activity之上
这样在跳转页面时就可以直接启动activity
而不是等动画执行完再启动
不知道我这个想法对吗。。。

再次感谢

**Comment by XunMengWinter** [comment]
那个，应该是涉及到 overridePendingTransition，我默认设置的是
 private int mEnterAnim = android.R.anim.fade_in, mExitAnim = android.R.anim.fade_out;
也就是在逐渐隐去，这个过程需要一点时间。可以通过在.go()之前调用.overridePendingTransition()方法以改变转场动画。
Toast那样不清楚诶，因为CircularAnim调用的是系统自带的ViewAnimationUtils.createCircularReveal(), 需要占用UI线程。

**Comment by qingchen1016** [comment]
您好！
感谢您的回答，经过的我验证，发现我的问题是设备原因导致的（之前用的测试机是三防手机 各项参数感人），可能ui绘制的比较慢一些，换到性能好点的手机上就完全没问题了。
再次感谢，问题可以关闭了。
