### ISSUE TITLE
关于fullactivity()的时间疑问

### ISSUE THREAD

**Issue by yxmark** [XunMengWinter/CircularAnim#33]
使用了fullactivity，然后在里面不管startanimator和returnanimator的duration设置多短，这两个动画中间似乎有一个有一个比较长的时间？就是，比如我点一个按钮触发fullactivity(实际上只是replace一个fragment), 然后会先快速出现覆盖全屏水波，然后停了大概两秒，然后水波收回，出现另外一个fragment。中间的那两秒的时间如何改？然后，是否可以设置然后水波不收回直接显示新的fragment?

**Comment by XunMengWinter** [comment]
postDelayed()造成的，在activity A -> activity B时，执行扩展动画，在重新回到 A 时，postDelayed()里的动画才会执行(这个很巧妙)。

所以，在fragment里面，用show()方法来控制一个一开始不可见的视图即可。

**Comment by yxmark** [comment]
谢谢讲解。我想在一个Activity里面从一个全屏幕的fragment打开另外一个全屏幕的fragment(通过fragment.replace())的话，用show好像就不能自定义设置那种铺满颜色的了好像？

**Comment by XunMengWinter** [comment]
我在demo中添加了Fragment的转换动画，你可以参考下～
[FragmentTestActivity](https://github.com/XunMengWinter/CircularAnim/blob/master/demo/src/main/java/top/wefor/circularanimdemo/fragment/FragmentTestActivity.java)

具体是通过一个新增一个View来实现，代码可能比Activity的跳转多了点～因为 为了与Activity或者Fragment等具体容器解耦合的，所以不额外添加api支持。

**Comment by yxmark** [comment]
谢谢大大！！
