### ISSUE TITLE
推荐 jitpack

### ISSUE THREAD

**Issue by twiceyuan** [XunMengWinter/CircularAnim#6]
jcenter 发布是挺烦的，而且会有数量限制，不介意可以试试 jitpack.io，直接在 github 上加个 tag，然后地址贴过去就可以了

**Comment by XunMengWinter** [comment]
thx~果然简单很多，

**Comment by XunMengWinter** [comment]
很神奇，我之前加的0.1.0的tag可以compile，但是后面的从0.2.0开始都compile不了了，代码都提交了的，不知道你有没有碰到这种情况，用的是jitpack.
compile 'com.github.XunMengWinter:CircularAnim:0.1.0'

compile 'com.github.XunMengWinter:CircularAnim:0.2.4'

**Comment by twiceyuan** [comment]
@XunMengWinter 碰到过，在失败图片的左边有个日志的标志，可以看到构建日志。

是不是升级了一些依赖库的版本？JitPack 对 support 库的更新可能稍微有一些延迟，如果是这个原因可以暂时降低到之前的版本试一下

**Comment by XunMengWinter** [comment]
可能是延迟的原因，不过0.2.0已经提交一两个小时了还是不行。没有升级其它库。

**Comment by XunMengWinter** [comment]
对了，我还怀疑是git的原因，因为昨天我还能用通过 git push origin --delete tag 0.2.2 来删除tag，今天这样子删除后但不生效～

**Comment by twiceyuan** [comment]
我看到 release 里面没有 0.2.0？

是要在 github 上发布一个 release 才有用了，只是添加 tag 貌似不可以。不是发布的 release 的话（比如用 commit 的 id），貌似要引用过一次 才会构建

**Comment by XunMengWinter** [comment]
我是这样子添加0.1.1的（最新版本）,但是还是不能用
git tag -a 0.1.1 94f3258

噢，0.2.0被我删除了，这次我删除后没有输 git push origin --tags，如果输入这行代码的话，删除的又会恢复。

**Comment by XunMengWinter** [comment]
https://jitpack.io/#XunMengWinter/CircularAnim/

在转圈圈，上面显示0.1.0可以～

**Comment by twiceyuan** [comment]
我 fork 了一个试了一下似乎没有问题 https://jitpack.io/#twiceyuan/CircularAnim/0.2.0 可能是 jitpack 的 bug，可以再发一个 release 重新构建一下试试

**Comment by XunMengWinter** [comment]
我compile不了你的     compile 'com.github.twiceyuan:CircularAnim:0.2.0'

你能compile我的吗，下面这个，我也compile不了～～
compile 'com.github.XunMengWinter:CircularAnim:0.2.1'

**Comment by XunMengWinter** [comment]
可以了可以了，Android Studio -> Invalidate and Restart , 然后再compile就OK了 👌 ～
