### ISSUE TITLE
你好！在Activity返回时，没有水波收缩动画

### ISSUE THREAD

**Issue by leguang** [XunMengWinter/CircularAnim#7]
@XunMengWinter 
你好！在Activity返回时，没有水波收缩动画
我看到在你的demo里MainActivity启动一个EmptyActivity时有一个水波扩散动画，然后以淡入淡出的形式出现另一个EmptyActivity，然后在退出EmptyActivity的时候，会有一个水波收缩的动画，然后显示出MainActivity。我看你的代码里写的是
`// 默认显示返回至当前Activity的动画.
                triggerView.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        Animator anim =
                                ViewAnimationUtils.createCircularReveal(view, cx, cy, finalRadius, 0);
                        anim.setDuration(finalDuration);
                        anim.addListener(new AnimatorListenerAdapter() {
                            @Override
                            public void onAnimationEnd(Animator animation) {
                                super.onAnimationEnd(animation);
                                try {
                                    decorView.removeView(view);
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                            }
                        });
                        anim.start();
                    }
                }, 1000);`

这段代码里是紧接着在启动EmptyActivity之后的，那为什么在退出EmptyActivity之后还能看到水波收缩的动画呢？不是在启动EmptyActivity之后，MainActivity里不会执行这段代码吗？是不是因为失去焦点，然后这个triggerView的动画就不执行，然后等从EmptyActivity返回到MainActivity后得到焦点就再继续执行，所以才造成退出EmptyActivity的时候可以看到triggerView的水波收缩动画呢？

我把EmptyActivity设置成透明的之后，再启动EmptyActivity会发现MainActivity中triggerView会在过一秒钟之后就自动执行收缩动画了。然后再按返回键就没有了之前的返回动画效果了（因为上面那段代码已经执行了）。

**Comment by leguang** [comment]
@XunMengWinter 
确实是因为设置Activity透明的问题，我把透明样式<item name="android:windowIsTranslucent">true</item>去掉之后就一切如你demo中所示
你的这个切换思路很不错哟
谢谢了

**Comment by XunMengWinter** [comment]
postDelayed()很好用，activity隐藏在后面就不会执行动画，会延迟到resume()执行 ^^~
